import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import Providers from "@/lib/providers/providers";
import BootstrapClient from "@/components/commons/bootstrap-client";

import "@interware/foundation/theme.css";
import "@interware/foundation/gradients.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--bs-body-font-family",
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <Providers>
          {children}
          <BootstrapClient />
        </Providers>
      </body>
    </html>
  );
}
